name: Serverplugin
version: '${project.version}'
main: codes.qdbp.serverplugin.Serverplugin
api-version: 1.19
authors: [ qdbp ]
description: Just my plugin for our server
website: https://qdbp.codes
commands:
  tode:
    description: Zeigt tode aller spieler
    usage: /tode <nameVonAnderenSpieler>
  features:
    description: Zeigt Infomessage an
    usage: /features
  toggleInfo:
    description: Toggles infotext
    usage: /toggleInfo
  backpack:
    description: opens a backpack
    usage: </backpack, /bp, /pv> <numberOfBackpack>
    aliases:
      - pv
      - bp
  afk:
    description: Let's you go afk
    usage: /afk <ort,grund,...>
  freecam:
    description: lets you use spectator mode
    usage: </freecam, /fc>
    aliases:
      - fc
  switchworld:
    description: switch worlds in freecam mode
    usage: </sw, /switchworld> <[overworld, ov, o], [nether, n], [end, e]>
    aliases:
      - sw
  craft:
    description: Use to open craft menu
    usage: /craft
    aliases:
      - c
  enderchest:
    description: Opens the players enderchest
    usage: </enderchest, /ec>
    aliases:
      - ec
  upgrade:
    description: Opens the upgrade menu
    usage: /upgrade