name: Serverplugin
version: '${project.version}'
main: codes.qdbp.serverplugin.Serverplugin
api-version: 1.19
authors: [ qdbp ]
description: Just my plugin for our server
website: https://qdbp.codes/
commands:

  features:
    description: Liste aller Features des Plugins
    usage: /features

  info:
    description: Informationen über die Features im Plugin
    usage: /info <feature name>

  tode:
    description: /info tode
    usage: /tode

  backpack:
    description: /info backpack
    usage: /backpack, /bp, /pv
    aliases:
      - pv
      - bp

  afk:
    description: /info afk
    usage: /afk <nachricht>

  freecam:
    description: /info freecam
    usage: /freecam, /fc
    aliases:
      - fc

  switchworld:
    description: /info switchworld
    usage: /switchworld, /sw <[overworld, ov, o], [nether, n], [end, e]>
    aliases:
      - sw

  enderchest:
    description: /info enderchest
    usage: </enderchest, /ec>
    aliases:
      - ec

  upgrade:
    description: /info upgrade
    usage: /upgrade

  skipNight:
    description: /info skipnight
    usage: /skipnight

  craft:
    description: /info craft
    usage: /craft, /c
    aliases:
      - c